package es.iesjandula.plataforma_streaming_equipo1.animations;

import es.iesjandula.plataforma_streaming_equipo1.utilities.ScreenUtilities;

public interface ViewAnimation
{

	public static void playingSerieMovie() throws InterruptedException 
	{
		
		Thread.sleep(1500);
		System.out.println(""
				+ "        __                                           __\r\n"
				+ "       (**)                                         (**)\r\n"
				+ "       IIII                                         IIII\r\n"
				+ "       ####                                         ####\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       ####                                         ####\r\n"
				+ "    ___IIII___                                   ___IIII___\r\n"
				+ " .-`_._\"**\"_._`-.                             .-`_._\"**\"_._`-.\r\n"
				+ "|/``  .`\\/`.  ``\\|                           |/``  .`\\/`.  ``\\|\r\n"
				+ "`     }    {     '                                 }    {     '\r\n"
				+ "      ) () (                                       ) () (\r\n"
				+ "      ( :: )                                       ( :: )\r\n"
				+ "      | :: |                                       | :: |\r\n"
				+ "      | )( |                                       | )( |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      ( () )                                       ( () )\r\n"
				+ "       \\  /                                         \\  /\r\n"
				+ "        \\/                                           \\/");
		Thread.sleep(400);
		ScreenUtilities.clearScreen();
		System.out.println(""
				+ "        __                                           __\r\n"
				+ "       (**)                                         (**)\r\n"
				+ "       IIII                                         IIII\r\n"
				+ "       ####                                         ####\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       ####                                         ####\r\n"
				+ "    ___IIII___                                   ___IIII___\r\n"
				+ " .-`_._\"**\"_._`-.                             .-`_._\"**\"_._`-.\r\n"
				+ "|/``  .`\\/`.  ``\\|                           |/``  .`\\/`.  ``\\|\r\n"
				+ "`     }    {     '                                 }    {     '\r\n"
				+ "      ) () (                                       ) () (\r\n"
				+ "      ( :: )                                       ( :: )\r\n"
				+ "      | :: |                                       | :: |\r\n"
				+ "      | )( |                                       | )( |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      ( () )                                       ( () )\r\n"
				+ "       \\  /                                         \\  /\r\n"
				+ "        \\/                Credits:                   \\/");
		Thread.sleep(400);
		ScreenUtilities.clearScreen();
		System.out.println(""
				+ "        __                                           __\r\n"
				+ "       (**)                                         (**)\r\n"
				+ "       IIII                                         IIII\r\n"
				+ "       ####                                         ####\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       ####                                         ####\r\n"
				+ "    ___IIII___                                   ___IIII___\r\n"
				+ " .-`_._\"**\"_._`-.                             .-`_._\"**\"_._`-.\r\n"
				+ "|/``  .`\\/`.  ``\\|                           |/``  .`\\/`.  ``\\|\r\n"
				+ "`     }    {     '                                 }    {     '\r\n"
				+ "      ) () (                                       ) () (\r\n"
				+ "      ( :: )                                       ( :: )\r\n"
				+ "      | :: |                                       | :: |\r\n"
				+ "      | )( |                                       | )( |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      ( () )                                       ( () )\r\n"
				+ "       \\  /               Credits:                  \\  /\r\n"
				+ "        \\/                                           \\/");
		Thread.sleep(400);
		ScreenUtilities.clearScreen();
		System.out.println(""
				+ "        __                                           __\r\n"
				+ "       (**)                                         (**)\r\n"
				+ "       IIII                                         IIII\r\n"
				+ "       ####                                         ####\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       ####                                         ####\r\n"
				+ "    ___IIII___                                   ___IIII___\r\n"
				+ " .-`_._\"**\"_._`-.                             .-`_._\"**\"_._`-.\r\n"
				+ "|/``  .`\\/`.  ``\\|                           |/``  .`\\/`.  ``\\|\r\n"
				+ "`     }    {     '                                 }    {     '\r\n"
				+ "      ) () (                                       ) () (\r\n"
				+ "      ( :: )                                       ( :: )\r\n"
				+ "      | :: |                                       | :: |\r\n"
				+ "      | )( |                                       | )( |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      ( () )              Credits:                 ( () )\r\n"
				+ "       \\  /                                         \\  /\r\n"
				+ "        \\/                                           \\/");
		Thread.sleep(400);
		ScreenUtilities.clearScreen();
		System.out.println(""
				+ "        __                                           __\r\n"
				+ "       (**)                                         (**)\r\n"
				+ "       IIII                                         IIII\r\n"
				+ "       ####                                         ####\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       ####                                         ####\r\n"
				+ "    ___IIII___                                   ___IIII___\r\n"
				+ " .-`_._\"**\"_._`-.                             .-`_._\"**\"_._`-.\r\n"
				+ "|/``  .`\\/`.  ``\\|                           |/``  .`\\/`.  ``\\|\r\n"
				+ "`     }    {     '                                 }    {     '\r\n"
				+ "      ) () (                                       ) () (\r\n"
				+ "      ( :: )                                       ( :: )\r\n"
				+ "      | :: |                                       | :: |\r\n"
				+ "      | )( |                                       | )( |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |              Credits:                 | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      ( () )                                       ( () )\r\n"
				+ "       \\  /                                         \\  /\r\n"
				+ "        \\/                Directed by:               \\/");
		Thread.sleep(400);
		ScreenUtilities.clearScreen();
		System.out.println(""
				+ "        __                                           __\r\n"
				+ "       (**)                                         (**)\r\n"
				+ "       IIII                                         IIII\r\n"
				+ "       ####                                         ####\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       ####                                         ####\r\n"
				+ "    ___IIII___                                   ___IIII___\r\n"
				+ " .-`_._\"**\"_._`-.                             .-`_._\"**\"_._`-.\r\n"
				+ "|/``  .`\\/`.  ``\\|                           |/``  .`\\/`.  ``\\|\r\n"
				+ "`     }    {     '                                 }    {     '\r\n"
				+ "      ) () (                                       ) () (\r\n"
				+ "      ( :: )                                       ( :: )\r\n"
				+ "      | :: |                                       | :: |\r\n"
				+ "      | )( |                                       | )( |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |              Credits:                 | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      ( () )                                       ( () )\r\n"
				+ "       \\  /               Directed by:              \\  /\r\n"
				+ "        \\/                                           \\/");
		Thread.sleep(400);
		ScreenUtilities.clearScreen();
		System.out.println(""
				+ "        __                                           __\r\n"
				+ "       (**)                                         (**)\r\n"
				+ "       IIII                                         IIII\r\n"
				+ "       ####                                         ####\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       ####                                         ####\r\n"
				+ "    ___IIII___                                   ___IIII___\r\n"
				+ " .-`_._\"**\"_._`-.                             .-`_._\"**\"_._`-.\r\n"
				+ "|/``  .`\\/`.  ``\\|                           |/``  .`\\/`.  ``\\|\r\n"
				+ "`     }    {     '                                 }    {     '\r\n"
				+ "      ) () (                                       ) () (\r\n"
				+ "      ( :: )                                       ( :: )\r\n"
				+ "      | :: |                                       | :: |\r\n"
				+ "      | )( |                                       | )( |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |              Credits:                 | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      ( () )              Directed by:             ( () )\r\n"
				+ "       \\  /                                         \\  /\r\n"
				+ "        \\/                                           \\/");
		Thread.sleep(400);
		ScreenUtilities.clearScreen();
		System.out.println(""
				+ "        __                                           __\r\n"
				+ "       (**)                                         (**)\r\n"
				+ "       IIII                                         IIII\r\n"
				+ "       ####                                         ####\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       ####                                         ####\r\n"
				+ "    ___IIII___                                   ___IIII___\r\n"
				+ " .-`_._\"**\"_._`-.                             .-`_._\"**\"_._`-.\r\n"
				+ "|/``  .`\\/`.  ``\\|                           |/``  .`\\/`.  ``\\|\r\n"
				+ "`     }    {     '                                 }    {     '\r\n"
				+ "      ) () (                                       ) () (\r\n"
				+ "      ( :: )                                       ( :: )\r\n"
				+ "      | :: |                                       | :: |\r\n"
				+ "      | )( |                                       | )( |\r\n"
				+ "      | || |              Credits:                 | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |              Directed by:             | || |\r\n"
				+ "      ( () )                                       ( () )\r\n"
				+ "       \\  /                                         \\  /\r\n"
				+ "        \\/                                           \\/");
		Thread.sleep(400);
		ScreenUtilities.clearScreen();
		System.out.println(""
				+ "        __                                           __\r\n"
				+ "       (**)                                         (**)\r\n"
				+ "       IIII                                         IIII\r\n"
				+ "       ####                                         ####\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       ####                                         ####\r\n"
				+ "    ___IIII___                                   ___IIII___\r\n"
				+ " .-`_._\"**\"_._`-.                             .-`_._\"**\"_._`-.\r\n"
				+ "|/``  .`\\/`.  ``\\|                           |/``  .`\\/`.  ``\\|\r\n"
				+ "`     }    {     '                                 }    {     '\r\n"
				+ "      ) () (                                       ) () (\r\n"
				+ "      ( :: )                                       ( :: )\r\n"
				+ "      | :: |                                       | :: |\r\n"
				+ "      | )( |                                       | )( |\r\n"
				+ "      | || |              Credits:                 | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |              Directed by:             | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      ( () )                                       ( () )\r\n"
				+ "       \\  /                                         \\  /\r\n"
				+ "        \\/                                           \\/");
		Thread.sleep(400);
		ScreenUtilities.clearScreen();
		System.out.println(""
				+ "        __                                           __\r\n"
				+ "       (**)                                         (**)\r\n"
				+ "       IIII                                         IIII\r\n"
				+ "       ####                                         ####\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       ####                                         ####\r\n"
				+ "    ___IIII___                                   ___IIII___\r\n"
				+ " .-`_._\"**\"_._`-.                             .-`_._\"**\"_._`-.\r\n"
				+ "|/``  .`\\/`.  ``\\|                           |/``  .`\\/`.  ``\\|\r\n"
				+ "`     }    {     '                                 }    {     '\r\n"
				+ "      ) () (                                       ) () (\r\n"
				+ "      ( :: )                                       ( :: )\r\n"
				+ "      | :: |                                       | :: |\r\n"
				+ "      | )( |                                       | )( |\r\n"
				+ "      | || |              Credits:                 | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |              Directed by:             | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      ( () )                                       ( () )\r\n"
				+ "       \\  /                                         \\  /\r\n"
				+ "        \\/                                           \\/");
		Thread.sleep(400);
		ScreenUtilities.clearScreen();
		System.out.println(""
				+ "        __                                           __\r\n"
				+ "       (**)                                         (**)\r\n"
				+ "       IIII                                         IIII\r\n"
				+ "       ####                                         ####\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       ####                                         ####\r\n"
				+ "    ___IIII___                                   ___IIII___\r\n"
				+ " .-`_._\"**\"_._`-.                             .-`_._\"**\"_._`-.\r\n"
				+ "|/``  .`\\/`.  ``\\|                           |/``  .`\\/`.  ``\\|\r\n"
				+ "`     }    {     '                                 }    {     '\r\n"
				+ "      ) () (                                       ) () (\r\n"
				+ "      ( :: )                                       ( :: )\r\n"
				+ "      | :: |                                       | :: |\r\n"
				+ "      | )( |                                       | )( |\r\n"
				+ "      | || |              Credits:                 | || |\r\n"
				+ "      | || |              Directed by:             | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      ( () )                                       ( () )\r\n"
				+ "       \\  /                                         \\  /\r\n"
				+ "        \\/                                           \\/");
		Thread.sleep(400);
		ScreenUtilities.clearScreen();
		System.out.println(""
				+ "        __                                           __\r\n"
				+ "       (**)                                         (**)\r\n"
				+ "       IIII                                         IIII\r\n"
				+ "       ####                                         ####\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       ####                                         ####\r\n"
				+ "    ___IIII___                                   ___IIII___\r\n"
				+ " .-`_._\"**\"_._`-.                             .-`_._\"**\"_._`-.\r\n"
				+ "|/``  .`\\/`.  ``\\|                           |/``  .`\\/`.  ``\\|\r\n"
				+ "`     }    {     '                                 }    {     '\r\n"
				+ "      ) () (                                       ) () (\r\n"
				+ "      ( :: )                                       ( :: )\r\n"
				+ "      | :: |                                       | :: |\r\n"
				+ "      | )( |                                       | )( |\r\n"
				+ "      | || |              Credits:                 | || |\r\n"
				+ "      | || |              Directed by:             | || |\r\n"
				+ "      | || |            David                      | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      ( () )                                       ( () )\r\n"
				+ "       \\  /                                         \\  /\r\n"
				+ "        \\/                                           \\/");
		Thread.sleep(1000);
		ScreenUtilities.clearScreen();
		System.out.println(""
				+ "        __                                           __\r\n"
				+ "       (**)                                         (**)\r\n"
				+ "       IIII                                         IIII\r\n"
				+ "       ####                                         ####\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       ####                                         ####\r\n"
				+ "    ___IIII___                                   ___IIII___\r\n"
				+ " .-`_._\"**\"_._`-.                             .-`_._\"**\"_._`-.\r\n"
				+ "|/``  .`\\/`.  ``\\|                           |/``  .`\\/`.  ``\\|\r\n"
				+ "`     }    {     '                                 }    {     '\r\n"
				+ "      ) () (                                       ) () (\r\n"
				+ "      ( :: )                                       ( :: )\r\n"
				+ "      | :: |                                       | :: |\r\n"
				+ "      | )( |                                       | )( |\r\n"
				+ "      | || |              Credits:                 | || |\r\n"
				+ "      | || |              Directed by:             | || |\r\n"
				+ "      | || |            David Martinez             | || |\r\n"
				+ "      | || |          ------------------           | || |\r\n"
				+ "      | || |                                       | || |\r\n"
				+ "      ( () )                                       ( () )\r\n"
				+ "       \\  /                                         \\  /\r\n"
				+ "        \\/                                           \\/");
		Thread.sleep(1000);
		ScreenUtilities.clearScreen();
		System.out.println(""
				+ "        __                                           __\r\n"
				+ "       (**)                                         (**)\r\n"
				+ "       IIII                                         IIII\r\n"
				+ "       ####                                         ####\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       ####                                         ####\r\n"
				+ "    ___IIII___                                   ___IIII___\r\n"
				+ " .-`_._\"**\"_._`-.                             .-`_._\"**\"_._`-.\r\n"
				+ "|/``  .`\\/`.  ``\\|                           |/``  .`\\/`.  ``\\|\r\n"
				+ "`     }    {     '                                 }    {     '\r\n"
				+ "      ) () (                                       ) () (\r\n"
				+ "      ( :: )                                       ( :: )\r\n"
				+ "      | :: |                                       | :: |\r\n"
				+ "      | )( |                                       | )( |\r\n"
				+ "      | || |              Credits:                 | || |\r\n"
				+ "      | || |              Directed by:             | || |\r\n"
				+ "      | || |            David Martinez             | || |\r\n"
				+ "      | || |          ------------------           | || |\r\n"
				+ "      | || |              Cooperators:             | || |\r\n"
				+ "      ( () )                                       ( () )\r\n"
				+ "       \\  /                                         \\  /\r\n"
				+ "        \\/                                           \\/");
		Thread.sleep(1000);
		ScreenUtilities.clearScreen();
		System.out.println(""
				+ "        __                                           __\r\n"
				+ "       (**)                                         (**)\r\n"
				+ "       IIII                                         IIII\r\n"
				+ "       ####                                         ####\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       ####                                         ####\r\n"
				+ "    ___IIII___                                   ___IIII___\r\n"
				+ " .-`_._\"**\"_._`-.                             .-`_._\"**\"_._`-.\r\n"
				+ "|/``  .`\\/`.  ``\\|                           |/``  .`\\/`.  ``\\|\r\n"
				+ "`     }    {     '                                 }    {     '\r\n"
				+ "      ) () (                                       ) () (\r\n"
				+ "      ( :: )                                       ( :: )\r\n"
				+ "      | :: |                                       | :: |\r\n"
				+ "      | )( |                                       | )( |\r\n"
				+ "      | || |              Credits:                 | || |\r\n"
				+ "      | || |              Directed by:             | || |\r\n"
				+ "      | || |            David Martinez             | || |\r\n"
				+ "      | || |           ------------------          | || |\r\n"
				+ "      | || |              Cooperators:             | || |\r\n"
				+ "      ( () )               Luis David              ( () )\r\n"
				+ "       \\  /                                         \\  /\r\n"
				+ "        \\/                                           \\/");
		Thread.sleep(1000);
		ScreenUtilities.clearScreen();
		System.out.println(""
				+ "        __                                           __\r\n"
				+ "       (**)                                         (**)\r\n"
				+ "       IIII                                         IIII\r\n"
				+ "       ####                                         ####\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       ####                                         ####\r\n"
				+ "    ___IIII___                                   ___IIII___\r\n"
				+ " .-`_._\"**\"_._`-.                             .-`_._\"**\"_._`-.\r\n"
				+ "|/``  .`\\/`.  ``\\|                           |/``  .`\\/`.  ``\\|\r\n"
				+ "`     }    {     '                                 }    {     '\r\n"
				+ "      ) () (                                       ) () (\r\n"
				+ "      ( :: )                                       ( :: )\r\n"
				+ "      | :: |                                       | :: |\r\n"
				+ "      | )( |                                       | )( |\r\n"
				+ "      | || |              Credits:                 | || |\r\n"
				+ "      | || |              Directed by:             | || |\r\n"
				+ "      | || |            David Martinez             | || |\r\n"
				+ "      | || |           ------------------          | || |\r\n"
				+ "      | || |              Cooperators:             | || |\r\n"
				+ "      ( () )               Luis David              ( () )\r\n"
				+ "       \\  /              Pablo Serrano              \\  /\r\n"
				+ "        \\/                                           \\/");
		Thread.sleep(1000);
		ScreenUtilities.clearScreen();
		System.out.println(""
				+ "        __                                           __\r\n"
				+ "       (**)                                         (**)\r\n"
				+ "       IIII                                         IIII\r\n"
				+ "       ####                                         ####\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       ####                                         ####\r\n"
				+ "    ___IIII___                                   ___IIII___\r\n"
				+ " .-`_._\"**\"_._`-.                             .-`_._\"**\"_._`-.\r\n"
				+ "|/``  .`\\/`.  ``\\|                           |/``  .`\\/`.  ``\\|\r\n"
				+ "`     }    {     '                                 }    {     '\r\n"
				+ "      ) () (                                       ) () (\r\n"
				+ "      ( :: )                                       ( :: )\r\n"
				+ "      | :: |                                       | :: |\r\n"
				+ "      | )( |                                       | )( |\r\n"
				+ "      | || |              Credits:                 | || |\r\n"
				+ "      | || |              Directed by:             | || |\r\n"
				+ "      | || |            David Martinez             | || |\r\n"
				+ "      | || |           ------------------          | || |\r\n"
				+ "      | || |              Cooperators:             | || |\r\n"
				+ "      ( () )               Luis David              ( () )\r\n"
				+ "       \\  /              Pablo Serrano              \\  /\r\n"
				+ "        \\/              Antonio Aceriano             \\/");
		Thread.sleep(1000);
		ScreenUtilities.clearScreen();
		System.out.println(""
				+ "        __                                           __\r\n"
				+ "       (**)                                         (**)\r\n"
				+ "       IIII                                         IIII\r\n"
				+ "       ####                                         ####\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       ####                                         ####\r\n"
				+ "    ___IIII___                                   ___IIII___\r\n"
				+ " .-`_._\"**\"_._`-.                             .-`_._\"**\"_._`-.\r\n"
				+ "|/``  .`\\/`.  ``\\|                           |/``  .`\\/`.  ``\\|\r\n"
				+ "`     }    {     '                                 }    {     '\r\n"
				+ "      ) () (                                       ) () (\r\n"
				+ "      ( :: )                                       ( :: )\r\n"
				+ "      | :: |                                       | :: |\r\n"
				+ "      | )( |                                       | )( |\r\n"
				+ "      | || |              Credits:                 | || |\r\n"
				+ "      | || |              Directed by:             | || |\r\n"
				+ "      | || |            David Martinez             | || |\r\n"
				+ "      | || |           ------------------          | || |\r\n"
				+ "      | || |              Cooperators:             | || |\r\n"
				+ "      ( () )               Luis David              ( () )\r\n"
				+ "       \\  /              Pablo Serrano              \\  /\r\n"
				+ "        \\/              Antonio Aceriano             \\/\n"
				+ "                          Juan Miguel                    \n");
		Thread.sleep(500);
		ScreenUtilities.clearScreen();
		System.out.println(""
				+ "        __                                           __\r\n"
				+ "       (**)                                         (**)\r\n"
				+ "       IIII                                         IIII\r\n"
				+ "       ####                                         ####\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       ####                                         ####\r\n"
				+ "    ___IIII___                                   ___IIII___\r\n"
				+ " .-`_._\"**\"_._`-.                             .-`_._\"**\"_._`-.\r\n"
				+ "|/``  .`\\/`.  ``\\|                           |/``  .`\\/`.  ``\\|\r\n"
				+ "`     }    {     '                                 }    {     '\r\n"
				+ "      ) () (         !THANKS FOR WATCHING!         ) () (\r\n"
				+ "      ( :: )                                       ( :: )\r\n"
				+ "      | :: |                                       | :: |\r\n"
				+ "      | )( |                                       | )( |\r\n"
				+ "      | || |              Credits:                 | || |\r\n"
				+ "      | || |              Directed by:             | || |\r\n"
				+ "      | || |            David Martinez             | || |\r\n"
				+ "      | || |           ------------------          | || |\r\n"
				+ "      | || |              Cooperators:             | || |\r\n"
				+ "      ( () )               Luis David              ( () )\r\n"
				+ "       \\  /              Pablo Serrano              \\  /\r\n"
				+ "        \\/              Antonio Aceriano             \\/\n"
				+ "                          Juan Miguel                    \n");
		Thread.sleep(1300);
		ScreenUtilities.clearScreen();
		System.out.println(""
				+ "        __                                           __\r\n"
				+ "       (**)                                         (**)\r\n"
				+ "       IIII                                         IIII\r\n"
				+ "       ####                                         ####\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       HHHH                                         HHHH\r\n"
				+ "       ####                                         ####\r\n"
				+ "    ___IIII___                                   ___IIII___\r\n"
				+ " .-`_._\"**\"_._`-.                             .-`_._\"**\"_._`-.\r\n"
				+ "|/``  .`\\/`.  ``\\|                           |/``  .`\\/`.  ``\\|\r\n"
				+ "`     }    {     '                                 }    {     '\r\n"
				+ "      ) () (         !THANKS FOR WATCHING!         ) () (\r\n"
				+ "      ( :: )                                       ( :: )\r\n"
				+ "      | :: |           ----> + 1 View              | :: |\r\n"
				+ "      | )( |                                       | )( |\r\n"
				+ "      | || |              Credits:                 | || |\r\n"
				+ "      | || |              Directed by:             | || |\r\n"
				+ "      | || |            David Martinez             | || |\r\n"
				+ "      | || |           ------------------          | || |\r\n"
				+ "      | || |              Cooperators:             | || |\r\n"
				+ "      ( () )               Luis David              ( () )\r\n"
				+ "       \\  /              Pablo Serrano              \\  /\r\n"
				+ "        \\/              Antonio Aceriano             \\/\n"
				+ "                          Juan Miguel                    \n");
		Thread.sleep(3000);
		ScreenUtilities.clearScreen();
	}
	
}
